### ISSUE TITLE
Disarming Enchant can Dupe Armour

### ISSUE THREAD

**Issue by TheRoboticHydra** [DaFuqs/Spectrum#13]
**Describe the bug**
Hitting another player with disarming enchant can dupe the armour they are wearing

**To Reproduce**
Hit another player with a disarming enchanted sword

**Expected behavior**
The player should lose the armour they were wearing or not work at all? not sure?

**Screenshots**
https://www.youtube.com/watch?v=Kdwo6djkl84

**Comment by DaFuqs** [comment]
This is fixed in the version that will be released today.

I find it more concerning how you got that enchantment in the first place, since it should only be available in Spectrums Enchanter. Getting it - and other Spectrum Enchantments - from other sources outside the mods progression will cause weird sequence breaking issues in general.

**Comment by TheRoboticHydra** [comment]
Got it via the Dark Enchanter.

**Comment by DaFuqs** [comment]
Thank you. Best to blacklist all of Spectrums enchantments in the dark enchanter.

I will hurry with the update. 👍

**Comment by DaFuqs** [comment]
Fixed in 1.2.0. (enchantments available via Dark Enchanter I cannot fix, tho :P)

**Comment by SomeAspy** [comment]
Armor duping still occurs as of v1.6.4-1.19.2-leisure_time

**Comment by DaFuqs** [comment]
Something something mod conflict
