### ISSUE TITLE
[Feature] Warning for [Spoilers]

### ISSUE THREAD

**Issue by Linguardium** [DaFuqs/Spectrum#132]
It would be great to have some in-game warning about the destruction about to befall the player during the Perfect Compound stage

https://github.com/TeamAOF/All-of-Fabric-6/issues/12

**Comment by Clonephaze** [comment]
Yeah, literally anything would be good. It's understandable that you would want to keep the whole "not discovered until you actually discover it" thing, but to potentially have your base/items/etc. destroyed because of a mod that hasn't been destructive up to that point is just unpleasant. Maybe as soon as you start the craft your character should "get an unpleasant feeling" and hint at stopping the process or let it continue at risk of destruction. That way you can keep it a secret until its about to break stuff.

**Comment by DaFuqs** [comment]
Yes, very much agree.
I will reqrite the midgame entries in the general part of the book to give it a bit more of a "descent into madness" touch and hint at this recipe being very powerful and risky

**Comment by DaFuqs** [comment]
done!
