### ISSUE TITLE
[BUG] Egg-laying Wooly Pig cannot be dyed when it's shaved

### ISSUE THREAD

**Issue by Jenny77** [DaFuqs/Spectrum#151]
This time I was messing around with a paintbrush and egg-laying wooly pigs. I used Ink Sling on them, and successfully dyed the wooly ones with it. But the one which is shaved just before dying them seems to be uneffected,with white hair on its head. I waited it to see if it's dyed or not, it turned out that the shaved one is not dyed. Is there anything wrong with them?

**Comment by DaFuqs** [comment]
That is a remnant how Sheep work: Sheep cannot be dyed when sheared, too, so I kept in for consistency's sake.
I actually thought about changing that for the Egg-laying Woold Pigs, but for reasons I can not remember anymore chose not to.

Making them dyeable while sheared should be pretty intuitive, since wooly pigs, contrary to sheep visually indicate the color change with their head wool. Players will get that visual feedback that sheep lack.

=> Will change that, thank you!

**Comment by Jenny77** [comment]
Not at all!
