### ISSUE TITLE
[BUG] Attempting to initialize a FabricBlockLootTableProvider object results in a crash

### ISSUE THREAD

**Issue by Librv** [DaFuqs/Spectrum#190]
**Describe the bug**
Trying to initialize a [FabricBlockLootTableProvider](https://github.com/FabricMC/fabric/blob/123f0c73d5e94c16e7e913add451325e0c1bc409/fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricBlockLootTableProvider.java) object (e.g. MyBlockLootTableProvider) while Spectrum (and its dependencies) is included in the same instance results in a crash at startup.

**To Reproduce**
Include [this example mod](https://github.com/Librv/fabric-example-mod/releases/tag/1.0.0-1.19.2) in a 1.19.2 instance together with Spectrum (1.6.10) and its dependencies. This is a simple mod that creates a `BlockLootTableProvider` object at initialization and nothing else, [see here](https://github.com/Librv/fabric-example-mod/blob/main/src/main/java/net/fabricmc/example/ExampleMod.java). 

Below is the mod list used and the versions for each dependency, which are also detailed in the logs.
![image](https://user-images.githubusercontent.com/73041325/236305193-1915e431-a828-4cb4-a2ab-06ae96ebb4d3.png)

**Expected behavior**
Game loading without issues. Note: provider isn't used, meaning that no data is being generated at any point.

**Mod version**
1.6.10

**Screenshots**

**Crash Report**
[crash-2023-05-04_21.01.40-client.txt](https://mclo.gs/ERj3KTr)
[latest.log](https://mclo.gs/BOf7tz3)

**Comment by DaFuqs** [comment]
Your example mod is adding loot tables at a point where mods have not finished initialisation yet.
Instead, you should load loot tables at the same time vanilla does - when loading a world.
Does the mod still crash, then?
(Can check in 3 days)

**Comment by Librv** [comment]
Moving the initialization for `BlockLootTableProvider` to client initialization fixes the crash, but why isn't initializing a standard [`LootTableProvider`](https://github.com/Librv/fabric-example-mod/blob/main/src/main/java/net/fabricmc/example/LootTableProvider.java) during mod initialization causing problems? 

Also, what loot tables are being created? I'm simply creating an instance of a provider that can't be run because it isn't added to any `DataGenerator`, meaning that no .json files will be created.

I also want to add that attempting to pass a loot builder created from `BlockLootTableGenerator` through `LootTableProvider` [(see here)](https://github.com/Librv/fabric-example-mod/blob/main/src/main/java/net/fabricmc/example/LootTableProvider.java#L36) creates the same exact crash, and it's worth noting that this generator class is extended by `FabricBlockLootTableProvider`. This generator class is all about methods for creating, as the name implies, block loot tables, but it also contains a static initializer block at the bottom that I think is worth looking at.

Thank you for your patience 👍

**Comment by DaFuqs** [comment]
BlockLootTableProvider loads the class ItemPredicate
...which triggers Spectrum's [Shears Mixin](https://github.com/DaFuqs/Spectrum/blob/1.19-deeper-down/src/main/java/de/dafuqs/spectrum/mixin/ItemPredicateMixin.java) to load
...which then loads the SpectrumItems class
...which then acts up, because the config has not been loaded yet (Since Spectrum's mod initializer has not yet run).

You can probably also trigger that crash by using a ItemPredicate in your `LootTableProvider`.

That mixin sadly is a remnant from minecraft/fabric not having a dedicated shears item tag, with `minecraft:shears` being hardcoded in lots of vanilla loot tables and is used in different variations in other mods, like [Botania](https://github.com/VazkiiMods/Botania/blob/1.19.3-wip/Fabric/src/main/java/vazkii/botania/fabric/mixin/ItemPredicateFabricMixin.java). Once https://github.com/FabricMC/fabric/pull/1287 is done that mixin can be ditched. 😊

**Comment by Librv** [comment]
Understood, I guess I'll be joining the wait for the shears tag! 😅
I'll look into having every provider done at client initialization from here on out.
Thanks for your help again, I'll be closing this.

**Comment by DaFuqs** [comment]
Happy to help!
