### ISSUE TITLE
[BUG] Server Side Item Id Spectrum:invisible_item_frame

### ISSUE THREAD

**Issue by PandemoniumCrow** [DaFuqs/Spectrum#203]
**Describe the bug**
Server Keeps having to skip an item called invisible item frame, an item that doesn't seem to show up at all in the files as a genuine item in the game.
it has been what seems to be the cause for crashes every do often and also clogs up the server logs A LOT Making troubleshooting other issues a pain.

**To Reproduce**
Run AOF6 Modpack server
Explore and monitor the server on CMD

**Expected behavior**
Not have to skip hundreds of entities called Invisible item frames? I am unsure what these even are???

**Mod version**
1.6.10

**Screenshots**
![image](https://github.com/DaFuqs/Spectrum/assets/74631742/4a215584-6c38-48f8-af42-baecd03d24ff)

Unsure if that works but here is what each line says on repeat:

[03:21:47] [Worker-Main-7/WARN]: Skipping Entity with id spectrum:invisible_item_frame

**Comment by DaFuqs** [comment]
One of the puzzle structures contains a saved entity `spectrum:invisible_item_frame` which is indeed not existent anymore, since it was renamed to `spectrum:invisible_phantom_frame` recently. This is fixed in the recent alphas. In the meantime you could for example override the structure nbt file via datapack with a version of the structure that does not contain that entity.

While this results in a bit of log spam since that entity fails to load when chunks are loaded (and rightfully so), I see no reason to believe that has anything to do with crashes?

**Comment by Linguardium** [comment]
since you know which puzzle structure, would you be able to link the puzzle structure and data path here so that folks can drop it in their kubejs/data/ folder to clear up the log spam.  This should not be causing any crashes though.

**Comment by DaFuqs** [comment]
This one:
https://github.com/DaFuqs/Spectrum/blob/1.19-leisure-time/src/main/resources/data/spectrum/structures/wireless_redstone_puzzle_structure.nbt

**Comment by DaFuqs** [comment]
Fixed in Spectrum's alpha builds.
