### ISSUE TITLE
[Feature] Allow pedestal structure tier upgrades without block removal

### ISSUE THREAD

**Issue by Linguardium** [DaFuqs/Spectrum#211]
currently, as you progress the pedestal tiers, there are certain blocks you have to remove as they are replaced by "more powerful blocks" or something, i dunno. 

When upgrading to the onyx pedestal, there are gem chiseled blocks in the floor of the structure that do not count towards the structure of the earlier tiers. this means that if you are upgrading bit by bit as the blocks are made, you can disable the pedestal accidentally by replacing these blocks too early.

What i would like to see is the base blocks have more tag inclusion so that, if i want my floor to have some chiseled moons decorating the floor, or amethyst chiseled calcite, it doesnt break the structure recognition. It would allow for a bit more creativity when designing the shrine.

**Comment by DaFuqs** [comment]
I'd love that and have already thought about it a lot in the past.

Sadly that is a bit of a limitation of Patchouli, since allowing a more extensive block tag for the floor will make the rendered ghost blocks toggle between all possible combinations, being pretty unsighty when constructing (and may prevent players from noticing the most obvious 'polished blocks with a bit of added detail' build).

**Comment by Linguardium** [comment]
Isn't this is a current issue and one that you have already handled for the pedestal (with the display and check multiblocks)

edit: oh i see, similar issue for a different problem. It would get a little unwieldy to have to create 3 multiblocks for the same structure, i suppose

**Comment by DaFuqs** [comment]
Done! Pedestals now also support the structures of their improved variants.
