### ISSUE TITLE
[BUG] Game crashes when loading world sometimes

### ISSUE THREAD

**Issue by oudehenky** [DaFuqs/Spectrum#262]
When loading a world the game crashes sometimes for unknown reasons, it appears theres an illegal character somewhere but it's still inconsistent to reproduce

Load a world and there's a chance it happens, I dont know WHAT causes it exactly.

The game loads normally

Spectrum 1.7.0

N/A

https://gnomebot.dev/paste/1161611531084124212 (crash report)

**Comment by oudehenky** [comment]
Here's another crash report w/o NEC just incase its needed

https://gnomebot.dev/paste/1161623208634634310

**Comment by oudehenky** [comment]
misclick :sob:

**Comment by DaFuqs** [comment]
The crash sadly is not caused by Spectrum, so I can't immediately help with that.

The crash seems to stem from an attempt to fix the vanilla bug MC-144761 (Particle Sprite Interpolation ignoring Alpha Channel). One of the mods that does this is [Incubus Concern](https://github.com/devs-immortal/Incubus-Core), which is bundled with Spectrum. Best to report the crash there.

This is the first time I'm seeing a crash like this, so it may also stem from a cross mod incompatibility? If you want to, try gradually removing mods until the crash does not occur anymore. But since you already mentioned the crash is only a chance, this may be very frustrating :<


Technical Info about the Crash:
net/minecraft/class_1058 => net/minecraft/client/texture/Sprite
net/minecraft/class_1058$class_4728 => Yarn: net/minecraft/client/texture/Sprite$Interpolation
net/minecraft/class_7764$class_4728 => Yarn: net/minecraft/client/texture/SpriteContents$Interpolation
