### ISSUE TITLE
[Feature] Add compatibility with Customizable Elytra

### ISSUE THREAD

**Issue by burrows4days** [DaFuqs/Spectrum#263]
The mod: https://legacy.curseforge.com/minecraft/mc-mods/customizable-elytra-fabric

I'm unsure if this would need to be done on your end or theirs, but it would be cool to see the spectrum banner patterns show up on elytras with this mod.

**Comment by DaFuqs** [comment]
Based legacy.curseforge user.

- it seems there is no documented way for other mods to register new banner patterns. It may be that just dropping new resources into their own namespace may work, but since that is not documented it may break anytime they change internals
- they ship with support for some other mods already

To have mod compat for the customizable elytras all in one place, it feels best for them to add the cross-mod stuff on their end.
Though if they do not want to, I may do some trickery.
