### ISSUE TITLE
[Feature] Allow Construction and Exchanging Staves to pull from Botania's Black Hole Talismans

### ISSUE THREAD

**Issue by Castone22** [DaFuqs/Spectrum#278]
Botania has an api interface that allows items to be pulled from things with its BlockProvider interface like the Black Hole Talisman.  It would be pretty slick if the Spectrum Construction and Exchanging Staves could do this.

https://github.com/VazkiiMods/Botania/blob/16d5cfa4f42d2ce166dc96aa4578b63ffcd44e66/Xplat/src/main/java/vazkii/botania/api/item/BlockProvider.java

https://github.com/VazkiiMods/Botania/blob/16d5cfa4f42d2ce166dc96aa4578b63ffcd44e66/Xplat/src/main/java/vazkii/botania/common/item/rod/ShiftingCrustRodItem.java#L66

**Comment by DaFuqs** [comment]
I've tried to use Botanias API functions in the past and failed sucessfully (hooking into the horn of the wild to fetch the player that breaks colored leaves)
I fear that's because of the different mappings used - yarn vs. mojmap that might not be doable. But when I got some time on my hands I will try again.

**Comment by eehunter** [comment]
I think it's possible to remap the botania jar in the dev environment? I know very little about mappings myself, unfortunately. I might be able to experiment with it in my fork and possibly try to implement it in a pull request? I probably won't get around to it, but maybe I'll give it a try.

**Comment by DaFuqs** [comment]
I've created the branch https://github.com/DaFuqs/Spectrum/tree/1.20.1-botania-playground some time ago to test some more advanced integrations (namely new items, levellable trinkets that lower botanias mana use, making colored leaves harvestable with botanias horns and the black hole talisman stuff, actually!)

It works rather well in prod. Running Spectrum + Botania in my dev env does not seem to work though, because of remapping errors.

Try it out, if you like!

**Comment by Abbie5** [comment]
Could the same functionality be added for the bottomless bundle?

**Comment by Castone22** [comment]
Probably make that a separate issue since the implementation of that would be entirely internal to spectrum

**Comment by DaFuqs** [comment]
done!
