### ISSUE TITLE
[Guidebook] Clearer Progression for Paltaeria

### ISSUE THREAD

**Issue by SUESS123** [DaFuqs/Spectrum#283]
Paltaeria gem recipe should be unlocked as soon a paltaeria itself it is due to the ores rarity and the seemingly low drop rates for gems, using fortune 3 I got almost 40 fragments before 1 gem

**Comment by Zenog400** [comment]
If you use Resonance, you automatically get gems from stratine/paltaeria, and you have access to resonance by the time you're able to get paltaeria

**Comment by SUESS123** [comment]
No you don't. The resonance pick can't mine paltaeria and the enchantment requires the gem itself.

**Comment by Zenog400** [comment]
Gilded books can copy the enchantment off the pickaxe without using the enchantment recipe

**Comment by SUESS123** [comment]
Fair, but thats still no good reason to not simplify progression by making the recipe easier.

**Comment by Azzyypaaras** [comment]
Eel dick moment
![image](https://github.com/DaFuqs/Spectrum/assets/20349662/096583f7-650a-46a5-b214-94a868deea21)

**Comment by burrows4days** [comment]
> Fair, but thats still no good reason to not simplify progression by making the recipe easier.

my two cents: making the recipe easier would detract from the discovery element of the mod. i think it's fine as-is, since you can infer the existence of palteria gems by noticing that palteria is a parallel to stratine (that realization was one of many fun moments in my blind playthrough), and then you can guarantee the drop by using the gilded book to strip resonance from the basic resonance pickaxe onto something more sturdy.

**Comment by Castone22** [comment]
> > Fair, but thats still no good reason to not simplify progression by making the recipe easier.
> 
> my two cents: making the recipe easier would detract from the discovery element of the mod. i think it's fine as-is, since you can infer the existence of palteria gems by noticing that palteria is a parallel to stratine (that realization was one of many fun moments in my blind playthrough), and then you can guarantee the drop by using the gilded book to strip resonance from the basic resonance pickaxe onto something more sturdy.

I actually had this realization too, the issue is if you can't see the recipe the altar won't let you perform the recipe. recipes that after pretty easy to infer from context would be nice to be able to discover by just experimenting around a little.  Slapping the same pattern for a stratine gem into the altar but for pateria and having it work and reveal the recipe would have given me a pretty large dopamine hit.

**Comment by DaFuqs** [comment]
I have taken a fair amount of time to think about this, as @burrows4days and @Castone22 make very good points.

## Conclusion
I do not think it would be good to reveal the recipe as soon as Paltaeria is discovered. Mainly because I want the player to collect their first Paltaeria gem on their own. Either through normal random drops, or by using resonance if they are really clever.

## Why?
When the player discovers Paltaeria for the first time it the End, they'll probably start off with a few fragments at first. Tthey might notice that they drop a bit oddly and quickly deduce that Paltaeria might be the Nether's counterpart to Stratine, and conclude that Stratine's gravity effect might also be reversed. Fun is to be had!

But even if the player is aware of the low-gravity effect they noticed with the fragments, they may not be prepared for the moment when their first Gem floats away from them into the sky, eliciting a small laugh or an embarassed head shake - or a Gotcha! if they thought of it and grabbed it as quickly as possible.


This leaves us with @Castone22's suggestion of allowing the player to discover the gem recipe on their own. Which sounds great, very much so! In reality, however, this is a bit tricky:
1. If a player notices that they can craft that recipe without it showing up in their recipe viewer, they might conclude that this applies to every recipe. This would mislead them.
2. I don't want players blindly trying out random recipes for hours on end, hoping an item combination may work, because that's no fun at all. In this case it might be kinda obvious, but with other recipes not so
3. Small technical limitation: Currently, recipes are either completely hidden (the "bake with the tears of your enemies" moment) or revealed through progression. There is no way yet to make recipes craftable after advancement x, but only appear after advancement y.

Leaving this open cause more input on the matter might be nice.

**Comment by Castone22** [comment]
Could also help to add another hint in the hint section for palteria that you can buy that mentions palteria seems to be highly reminiscent of stratine that stays highlighted in the ~~stratine~~ palteria hint section until you find your first gem

**Comment by DaFuqs** [comment]
Definitely a good call, since there is still something left to discover. Done!
