### ISSUE TITLE
[BUG] On 1.19.2, with some mods and data packs that change the depth of oceans, some of your structures don't touch the ocean floor

### ISSUE THREAD

**Issue by Sunconure11** [DaFuqs/Spectrum#306]
**Describe the bug**
Your structures will sometimes float underwater.

**To Reproduce**
Use various mods and data packs that alter gen

**Expected behavior**
Structures to be flush with the ocean floor

**Mod version**
1.7.3-1.19.2

**Screenshots**
![image](https://github.com/DaFuqs/Spectrum/assets/5614902/d2802edd-7a34-4245-aa17-0d12d8e6e1b7)

**Crash Report**
N/A

Also, unrelated, but I ran into this with polished basalt. Don't know why.

![image](https://github.com/DaFuqs/Spectrum/assets/5614902/6c9fe050-7bf4-42ca-8bab-2bf46eb63691)

**Comment by Zenog400** [comment]
The first one I can guarantee has nothing to do with any worldgen mods, because that's how it generates in vanilla. This is the deepslate variant of the same structure on the official server (at roughly -180, -480 if you want to check for yourself), which has no worldgen mods, fully exposed because they generate between certain Y-values and the ocean is deep enough that it generates above the ocean floor.
![image](https://github.com/DaFuqs/Spectrum/assets/41298161/f2777e70-4acd-46cc-bf46-aa833a74cc87)


The second is likely something to do with some other mod in your pack, because your screen looks like you're a cartoon character about to have a flashback with how much rippling it's doing, and that's definitely not from Spectrum.

**Comment by Sunconure11** [comment]
The rippling is from Psychedelicraft. I found what was causing the shader issue though.

https://modrinth.com/datapack/deeper-oceans

This is the data pack I'm using for deeper oceans.

https://modrinth.com/mod/configurable-caves

I'm also using this for caves.

**Comment by Zenog400** [comment]
Okay so that's cool, but this isn't a bug. The structures just spawn between certain Y values, and if an ocean is deep enough, they're exposed because it's deeper than that Y value. This happens to the Spectrum structures in vanilla worldgen too. It even happens with strongholds in pure vanilla gameplay.

**Comment by DaFuqs** [comment]
Improved in 1.7.4 (only for 1.20.1 atm, though. But I might backport that at the start of next year)
