### ISSUE TITLE
[BUG] Crash at Hint

### ISSUE THREAD

**Issue by TheButterbrotMan** [DaFuqs/Spectrum#31]
**Describe the bug**
If i open a hint, game is crashing.

**To Reproduce**
Install https://www.curseforge.com/minecraft/modpacks/deathdusk
Open a hint in book

**Expected behavior**
Hint opening

**Mod version**
spectrum-1.2.8-1.18.1-midgame9.jar

**Crash Report**
https://bytebin.lucko.me/yGpCFotkhk

**Comment by DaFuqs** [comment]
that happens when the world time on the client is going backwards. Any idea what could cause this?

**Comment by Gamerbolts** [comment]
Same thing happened to me and I checked here and see that it seems you created a workaround. Will this be coming out soon? Only thing I can think of time wise is i had the gamerule doDaylightcycle set to false so it was constantly noon.

**Comment by DaFuqs** [comment]
Spectrums Discord has an Alpha released since today. I am just waiting on some textures now. So: soon. Albeit I cant give a conccrete day right now. You would have to scream at Azzy for that. 

That said investigating what causes the time backdating in that pack would be good in general. I can see many mods rhat calculate time passed having similar issues.
