### ISSUE TITLE
[BUG] Server crash without FTBChunks

### ISSUE THREAD

**Issue by Kisuny** [DaFuqs/Spectrum#388]
**Describe the bug**
When a player tries to put light with the staff of light the server crashes.

The reason is that I removed the FTBChunks mod, for many reasons, but we still have the mod ftb-xmod-compat-fabric-1.2.3 for REI compat and FTB quests compat, removing ftb-xmod-compat-fabric-1.2.3 solves the problem, but we need it…

**Minecraft version**
1.19.2

**Mod version**
spectrum-1.7.6-deeper-down

**Crash Report**

[crash-2024-05-06_14.07.38-server.txt](https://github.com/DaFuqs/Spectrum/files/15221460/crash-2024-05-06_14.07.38-server.txt)

**Comment by DaFuqs** [comment]
The cause of the crash is pretty much what you described already and lies in ftb-xmod-compat-fabric.
What happens here is:
1. Player places block
2. Spectum asks CommonProtectionAPI if the player is allowed to place a block there
3. CommonProtectionAPI asks ftbxmodcompat
4. ftbxmodcompat wants to ask FTBChunks, but since that mod is not present, you get a crash

To resolve that issue, ftbxmodcompat will need to check if FTBChunks is actually installed, before trying to ask them, or telling CommonProtectionAPI it is able to handle block protection.

**Comment by DaFuqs** [comment]
@desht, pretty please? I can't open an issue for you, since https://github.com/FTBTeam/FTB-XMod-Compat does not have a public issue tracker

**Comment by desht** [comment]
https://github.com/FTBTeam/FTB-Mods-Issues/issues/ is the central place to create issues for all FTB mods. A separate issue tracker for each mod would be a nightmare to keep track of.

I thought this had been fixed, but it turns out the fix was only applied in 1.20.1.  I'll get the fix backported to 1.19 today and get a release out.

**Comment by DaFuqs** [comment]
Thank you!
