### ISSUE TITLE
[BUG] Guidebook Loading Error with Stackable Flowers installed

### ISSUE THREAD

**Issue by CrazedTinkerer** [DaFuqs/Spectrum#415]
**Describe the bug**
The guidebook fails to load when [Stackable Flowers](https://modrinth.com/mod/stackable-flowers) is installed. Likely related, I also got a crash when opening the creative inventory with only Spectrum and Stackable Flowers, although the crash didn't happen when I had a bunch of other mods enabled.

**To Reproduce**

1. Install Spectrum, its dependencies, and [Stackable Flowers](https://modrinth.com/mod/stackable-flowers).
2. Open the Guidebook
3. There should be an error page

**Expected behavior**
The Guidebook should load correctly.

**Minecraft version**
1.20.1

**Mod version**
1.7.11

**Screenshots**
![image](https://github.com/DaFuqs/Spectrum/assets/110867557/d0951ada-9ff9-4662-b985-c7f5566d7e66)

**Crash Report**
[log.txt](https://github.com/user-attachments/files/15813572/log.txt)

**Comment by DaFuqs** [comment]
I can confirm the crash and that it happens mostly by random.

Sadly I can not help with this one. Stackable Flowers gets funky with the flower blocks and their suspicious brew effects. You would also get a rare crash when getting some Suspicious Stew from a cow, so that one should better be fixed on their end.
