### ISSUE TITLE
[BUG] Game occasionally crashes when trying to enter a world

### ISSUE THREAD

**Issue by GameOnne** [DaFuqs/Spectrum#420]
**Describe the bug**
Trying to enter a world (no matter if its singleplayer or a server) will sometimes crash your game instead. Surprisingly, restarting Minecraft sometimes fixes this issue.

**To Reproduce**
Enter a world OR connect to a server.

**Expected behavior**
The loading screen should advance past "Loading world" and actually load the world.

**Minecraft version**
1.19.2

**Mod version**
1.7.11

**Crash Report**
[crash.txt](https://github.com/user-attachments/files/15916267/crash.txt)

**Comment by DaFuqs** [comment]
Unfortunately, the crash log is not very informative and does not give any indication of what the exact error might be, sorry.
It does not even reference Spectrum code. Is it possible that notehoughcrashes intercepts the error in a way? A full log might have more information.
It definitely is something related to particles, so any idea what could mess with that? dashloader comes to mind, since it caused particle related crashes in the past.

**Comment by GameOnne** [comment]
You're absolutely right, it was dashloader. Removing it fixed the issue once and for all.
The reason I reported this here in the first place is because NEC blamed Incubus Core, which is integrated into Spectrum.

**Comment by DaFuqs** [comment]
Thank you for the update.
