### ISSUE TITLE
[BUG] Crash on Server when right clicking Purple Pedestal

### ISSUE THREAD

**Issue by Gamerbolts** [DaFuqs/Spectrum#523]
**Describe the bug**
I created a modpack and am hosting a server. My users reported to me that they all crashed when right-clicking the Purple Pedestal. They can use the Orange One just fine, it is just the Purple one causing crashing. They broke the Pedestal and placed it back down and it worked. But the crashlog is below.

**To Reproduce**
Install PXC Cobblemon
Place down Purple Pedestal
Right click

**Expected behavior**
It to work

**Minecraft version**
Fabric 1.20.1

**Mod version**
1.7.16-deeper-down

**Crash Report**
[PurplePigmentTableCrashLog.txt](https://github.com/user-attachments/files/17442705/PurplePigmentTableCrashLog.txt)

**Comment by DaFuqs** [comment]
The game crashed from trying to get the item of an empty (null) item stack.
Sadly I can't help with that one, sorry. The source of the crash is another mod.

The crash seems to be caused by `io.github.xiaocihua.stacktonearbychests.LockedSlots.refresh()`, which is your `stack-to-nearby-chests-mc1.20.1-0.5.10.jar`

**Comment by Gamerbolts** [comment]
Thanks for looking into that. I'll post this on their github. Love the mod btw it's my wife and my favorite mod in Minecraft.
