### ISSUE TITLE
[BUG] Game crashes when spectrum skull is equipped in cosmetic helmet slot

### ISSUE THREAD

**Issue by Flixp** [DaFuqs/Spectrum#53]
**Describe the bug**
Every time you open your inventory after you equipped a spectrum skull in the cosmetic helmet slot (from the "cosmetic armor" mod) the game crashes/closes without error message. (i think when you look at someone with the skull as helmet too)

I use another quality modpack 2 if its important and will report this bug in the aqm2 issue page aswell

edit: F5 crashes game too (I assume seeing another player with the skull on does the same?)

**To Reproduce**
Equip spectrum skull in cosmetic helmet slot

**Expected behavior**
same as equipping the skull in normal helmet slot. (Game not crashing lol)

**Mod version**
spectrum: v1.2.8-1.18.1-midgame9
cosmetic armor: v1.2.1

**Screenshots**

**Crash Report**
If it is a crash bug add your crash log here
[crash-2022-04-11_19.10.28-client.txt](https://github.com/DaFuqs/Spectrum/files/8466397/crash-2022-04-11_19.10.28-client.txt)
[crash-2022-04-11_19.24.34-client.txt](https://github.com/DaFuqs/Spectrum/files/8466398/crash-2022-04-11_19.24.34-client.txt)

**Comment by TheRanker** [comment]
this also happens with 1.18.2 version of the mods.
Spectrum 1.3.1-1.18.2-midgame16-trinkets-brewing
[crash-2022-04-15_20.39.37-client.txt](https://github.com/DaFuqs/Spectrum/files/8498868/crash-2022-04-15_20.39.37-client.txt)

**Comment by dandin87** [comment]
The cosmetic armor slot mod crashes with many things that are left to modpacks dev to block from being used in the slot with tags. This of course is an impossible task to find all the things that crash. We removed the mod from All of Fabric 5 because of this same crashing issue. Its not worth the effort of finding and preventing all the things that can trigger the mod to crash.

**Comment by DaFuqs** [comment]
fixed
