### ISSUE TITLE
[BUG] mixin crash on servers

### ISSUE THREAD

**Issue by TheRanker** [DaFuqs/Spectrum#55]
**Describe the bug**
Mixin conflict. Causes shulker box crash.  Piglin brain mixin. 

**To Reproduce**
Break a shulker box

**Expected behavior**
Not crash? Lol

**Mod version**
spectrum-1.3.1-1.18.2-midgame16-trinkets-brewing.jar

**Screenshots**
N/A

**Crash Report**
https://bytebin.lucko.me/uBIUxJdg5P

**Comment by TheRanker** [comment]
Update.. happens with normal chests too.

**Comment by DaFuqs** [comment]
I could not reproduce that with Spectrum and utility mods alone. Can you try removing mods to find out what is the crashing combo and append the whole latest.log, please? Then I can get it fixed

**Comment by TheRanker** [comment]
happens with deathdusk modpack mostly. he has about 100 crashs from that mixin error. and sorta points to spectrum.  i am unable to replicate it in my modpack.

**Comment by AverageTurtle** [comment]
Hi so I am having this same issue but with spectrum-1.3.3-1.18.2-midgame18-trinkets-brewing
I see this was already marked mod compat and I have a lot of mods installed figured I would leave a log and crash report incase someone has the patience to figure out what mod is not compatible because I am not that patient atm

Also idk if I attached these files correctly never attached files on github lol
[crash-2022-05-09_07.35.09-client.txt](https://github.com/DaFuqs/Spectrum/files/8651246/crash-2022-05-09_07.35.09-client.txt)
[latest.log](https://github.com/DaFuqs/Spectrum/files/8651248/latest.log)
