### ISSUE TITLE
Clashes with Spectrum and Create through Sinytra

### ISSUE THREAD

**Issue by MrCheeseyman** [DaFuqs/Spectrum#611]
**Describe the bug**
Could not execute entrypoint stage 'main' due to errors, provided by 'spectrum' at 'de.dafuqs.spectrum.SpectrumCommon'

I do have issues with this from Origins too, however it all seems to stem from the error that occurs above 

**To Reproduce**
Have the following mods installed.

- Sinytra Connector  - Forge
- Cloth Config - Forge 
- Connector Extras - Forge
- Create - Froge
- Forgified Fabric
- Patchouli - Forge
- Revelationary - Fabric
- Spectral Decorations - Fabric
- Spectrum - Fabric
- Trinkets - Fabric
- Exclusions Lib - Version 0.6 - Fabric

**Expected behavior**

To load up as normal.

**Minecraft version**
Minecraft version 1.20.1
Forge version - 47.3.0

**Mod version**
Which version of the mod are you currently using?
Current versions of everything except Exclusions Lib

**Screenshots**

**Crash Report**
[crash-2024-11-28_10.56.08-client.txt](https://github.com/user-attachments/files/17946977/crash-2024-11-28_10.56.08-client.txt)

**Comment by Gronglegrowth** [comment]
Disable the Create integration in Spectrum's config (add `"create"` to `"IntegrationPacksToSkipLoading"`) to get the game to load.

**Comment by MrCheeseyman** [comment]
> Disable the Create integration in Spectrum's config (add `"create"` to `"IntegrationPacksToSkipLoading"`) to get the game to load.

Might I ask how you came to this conclusion? This is so that I could learn from this and try to use this method in the future to apply it to other problems that might arise when it relates to this

**Comment by Gronglegrowth** [comment]
On line 43, there is `Caused by: java.lang.NoSuchFieldError: FLOW`. Directly below this is Spectrum trying to load Create integration - hold on I just noticed you are using Spectrum 1.7.16 despite you saying you were on latest?

Anyway, just those two are enough to confirm that it's the Create integration breaking on Connector, so you either can remove Create, downgrade Spectrum, or keep both mods as they are and just disable the integration. ~~Though I'm curious if it still happens on Spectrum 1.8.0, I haven't tried using it with Create via Connector myself yet.~~ Edit: I just checked and it is automatically disabled on that version if Connector is loaded.

**Comment by MrCheeseyman** [comment]
I might've accidentally uploaded the wrong file ooops, however that did solve the initial issue that I did have which is amazing, I really appreciate it 👍

**Comment by DaFuqs** [comment]
Also downgrade Exclusions Lib to 0.5, since the newest release crashes on Forge, if that was not the initial issue you mentioned.

**Comment by Gronglegrowth** [comment]
No, 0.6 works on it.

**Comment by DaFuqs** [comment]
Might have messed up the versions in my mind then ✅
