### ISSUE TITLE
[BUG] Memory Leak Occurs After Installing Spectrum Mod

### ISSUE THREAD

**Issue by SAILQAQ** [DaFuqs/Spectrum#644]
**Describe the bug**
A memory leak occurs on the server after running for a period of time with the Spectrum mod installed. This issue does not occur when the Spectrum mod is not installed.

**To Reproduce**
Start the server and allow it to run for a period of time. Monitor server memory usage. Observe a gradual increase in memory consumption over time.

**Expected behavior**
The server should not experience a memory leak.

**Minecraft version**
1.20.1

**Mod version**
1.8.0

**Screenshots**
![1](https://github.com/user-attachments/assets/9cda48ae-e804-423f-853b-c3c2560405f5)
The screenshots provided suggest a potential connection to the Create mod's Deployer and the Trinkets mod. Please investigate potential interactions between these mods and Spectrum.

**Comment by Azzyypaaras** [comment]
What the fuck

**Comment by DaFuqs** [comment]
Are we talking minutes or hours here?

Spectrum does not interact with deployers at all.  But since deployers are fake players, they indeed have a trinkets inventory, hence the connection here.

I cannot see what Spectrum would have to do in all of this, though, since all Spectrum does it register a few additional Trinket slots via json and a few Trinkets the Deployer obviously does not have them equipped.
