### ISSUE TITLE
[Feature] let kelp grow in liquid crystal

### ISSUE THREAD

**Issue by D3thBr1ng3r** [DaFuqs/Spectrum#646]
quitoxic and mermaid gems can grow in lc so let kelp >:(

**Comment by imreallybadatnames** [comment]
sog yourself

**Comment by DaFuqs** [comment]
Fluid logging in vanilla MC is a lot more complicated than I would like it to be.
- Every single block has custom code for every fluid it can be logged with, making it difficult for existing blocks to be logged with new fluids, since each one needs to be handled separately with lots of edge cases if the liquid is infinite or not, if liquid can be removed from it with a bucket, ...
- Then there is the issue of block states. Kelp (with the blocks `kelp` and `kelp_plant`) has an age state from 0-25. Multiply that with the amounts of fluids it should be logged with (liquid crystal, mud, ...) makes the required block states grow immensely for each block

And once we add it for kelp, we will set the expectation that every fluid loggable block (including plants, but also stairs, slabs, ...) should be able to be liquid crystal or <insert other fluid> logged.
Right now I do not feel like that, sorry 😅

But I have seen other mods out there that can do something like that. Maybe one of those suits your taste!
